apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-client
spec:
  selector:
    matchLabels:
      app: app-client
  replicas: 1
  template:
    metadata:
      labels:
        app: app-client
    spec:
      containers:
        - name: app-client
          image: app-client:new
          imagePullPolicy: Never
          ports:
            - containerPort: 3000


---


apiVersion: v1
kind: Service
metadata:
  name: app-client
spec:
  type: LoadBalancer
  ports:
    protocol: TCP
    port: 80
    targetPort: 3000
    name: http
  selector:
    app: app-client
