apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-client
spec:
  selector:
    matchLabels:
      app: app-client
  replicas: 1
  template:
    metadata:
      labels:
        app: app-client
    spec:
      containers:
        - name: app-client
          image: app-client:new
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
